####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                  __    __   __        ___         __   __    __   __    __                   | #
# |                 |__)  |__  |__  |__|   |   \  /  |__  /__`  |__) |__)  |  |                  | #
# |                 |__)  |__  |__  |  |  _|_   \/   |__  .__/  |    |  \  |__|                  | #
# |                                                                                              | #
# |                                                           by OliPulse                        | #
# |                                                                                              | #
# |               Please follow the instructions noted above every setting.                      | #
# |               For support, please join the Discord server: https://discord.gg/47YEbMm        | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################


#The lore line above the bees for BeehivesPro items
beehive-item-bees-lore: "&6* &e&nBees&r &6*"
#The name above the of the bees, placeholders %BEE_NAME% and %BEEHIVE_NAME% can be used here.
#Set this to empty '' if you don't want your bees to have names.
bee-name-format: "%BEE_NAME% &f~ %BEEHIVE_NAME%"
#Enable this to let players rename bees with a name tag and keep their hives displayed behind their name.
enable-bee-renaming: true
#The format in which the bee's hive will be behind it's name when renamed (if it's hive has a name).
bee-renamed-hive: " &f~ %BEEHIVE_NAME%"
#The max level that BeehivesPro beehives can reach
beehive-max-level: 10

#The message you get in chat when right clicking a beehive. Placeholders %HONEY_LEVEL% and %MAX_HONEY_LEVEL% can be used.
beehive-honey-level-message: "&6Honey Level: %HONEY_LEVEL%&e/&6%MAX_HONEY_LEVEL%"
#The message players get when they use shears on a BeehivesPro beehive. Placeholder %AMOUNT% may be used.
beehive-shear-message: "&7You harvested &e%AMOUNT% &6Honeycombs"
#The message players get when they use glass bottles on a BeehivesPro beehive. Placeholder %AMOUNT% may be used.
beehive-bottle-message: "&7You harvested &e%AMOUNT% &6Honey Bottles"

#Enable or disable the harvesting of honey blocks from a BeehivesPro beehive.
harvest-honey-blocks: true
#The minimum level a beehive has to be before you can harvest honey blocks from it.
harvest-honey-blocks-minimum-level: 4
#The amount of blocks you will harvest at the harvest-honey-blocks-minimum-level. It will increase by 1 block for every level above.
harvest-honey-blocks-start-amount: 1
#The harvesting tool that must be used to harvest the honey blocks.
#List of valid item types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
harvest-honey-blocks-tool: GOLDEN_HOE
#The message players get when they harvest honey blocks from a BeehivesPro beehive. Placeholder %AMOUNT% may be used.
harvest-honey-block-message: "&7You harvested &e%AMOUNT% &6Honey Blocks"

#Enable or disable the custom animation when harvesting from a BeehivesPro beehive.
#The higher the level of the beehive, the more particles will spawn.
beehive-harvest-animation: true

#Enable or disable the ability for players to level up their BeehivesPro beehives with level tokens.
#You can get these tokens by using the command /bp addtokens <player> <amount>
enable-beehive-level-tokens: true
#List of valid item types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
beehive-level-token-item: HONEYCOMB
beehive-level-token-name: "&bBeehive Enhancer"
beehive-level-token-lore:
  - ""
  - "&7Use this on a &bBeehive &7to level it up!"
  - "&7Rarity: &bUncommon"
  - "&7Category: &fConsumable"
#Enable or disable the ability for players to craft BeehivesPro level tokens.
enable-beehive-level-tokens-crafting: true
beehive-level-token-crafting-recipe:
  #Set shapeless-recipe to true if the placement of the items in the crafting grid DOESN'T matter.
  #Set shapeless-recipe to false if the placement of the items in the crafting grid DOES matter.
  shapeless-recipe: false

  #When shapeless-recipe is set to false, the number represents the location in the crafting grid. The Item material comes behind it.
  #Crafting table positions from left to right: Top row: 1 2 3, Middle row: 4 5 6, Bottom row: 7 8 9
  #List of valid item types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  #In this default example the recipe is 8 honey blocks surrounding 1 diamond block in the middle.
  recipe:
    1: AIR
    2: HONEYCOMB
    3: AIR
    4: HONEYCOMB
    5: DIAMOND
    6: HONEYCOMB
    7: AIR
    8: HONEYCOMB
    9: AIR

  #When shapeless-recipe is set to true, the items should be set like it this example. Here the number represents the amount needed.
  #In this example the location of the blocks doesn't matter, you just need 8 honey blocks and 1 diamond block.
#  recipe:
#    HONEY_BLOCK: 8
#    DIAMOND_BLOCK: 1

#The message that gets sent when a player levels up a BeehivesPro beehive. Placeholder %NEW_LEVEL% may be used.
beehive-level-up-message: "&fLeveled up to &7lv.&b%NEW_LEVEL%"
#A lists of commands that you can run when someone upgrades a beehive. Placeholder %PLAYER% may be used.
beehive-level-up-commands:
  - ""
  - ""
#The message that gets sent when a beehive hits the minimum level required to harvest honey blocks from it.
unlock-honey-block-harvest-message: "&7You can now harvest &bHoney Blocks &7by using a &bGolden Hoe"
#The message that gets sent when someone tries to level up a maxed out beehive.
beehive-max-level-message: "&bThis beehive is already max level!"
#Enable or disable the custom animation when a BeehivesPro beehive is leveled up.
beehive-level-up-animation: true

#Enable or disable the mechanic where people can upgrade their own crafted beehives with beehive leveling tokens without having to use any command.
enable-vanilla-beehive-upgrade: true
#The preset that a vanilla beehive will become when upgraded to a BeehivesPro beehive.
vanilla-beehive-upgrade-preset: "default"
#Determines whether the newly upgraded beehive will spawn the bees listed in the preset it became.
vanilla-beehive-spawns-bees-when-upgraded: true

#These are the beehive presets that you can give to yourself in game with the command '/bp give <player> <presetName> <amount>"
beehive-presets:
  #This is the name of the preset that should be used in the command, you may use any name you want.
  'default':
    #Name of the beehive.
    beehive-name: "&6Beehive"
    #Starting level of the beehive. (Can be upgraded with leveling tokens)
    level: 1
    #The bees that will spawn when placing this beehive. Do not add more than 3 bees!
    bees:
      - "&eBee"
      - "&eBee"
      - "&eBee"
  'sky':
    beehive-name: "&bSky Hive"
    level: 1
    bees:
      - "&fGuard"
      - "&bWorker"
      - "&dQueen"
  'oceanic':
    beehive-name: "&1Oceanic Hive"
    level: 1
    bees:
      - "&fGuard"
      - "&bWorker"
      - "&dQueen"
  'desert':
    beehive-name: "&eDesert Hive"
    level: 1
    bees:
      - "&fGuard"
      - "&bWorker"
      - "&dQueen"
  'earth':
    beehive-name: "&6Earth Hive"
    level: 1
    bees:
      - "&fGuard"
      - "&bWorker"
      - "&dQueen"
  'dark':
    beehive-name: "&8The Dark Court"
    level: 4
    bees:
      - "&fWorker"
      - "&bSoldier"
      - "&dQueen"

  'high':
    beehive-name: "&eThe High Court"
    level: 4
    bees:
      - "&fWorker"
      - "&bSoldier"
      - "&dQueen"
  'hivemind':
    beehive-name: "&4The Hivemind"
    level: 4
    bees:
      - "&fDrone"
      - "&bEnforcer"
      - "&dOverseer"
