# Global settings.
BlacklistedWorlds:
- put_here_worlds
- that_you_want_blacklisted
BlacklistedWGRegions:
- put_here_regions
- that_you_want_blacklisted
Global:
  Notify: true
  SingleItemDrops: false
  SingleItemKeeps: false
  SlotBasedRecovery: false
  UseTheOrMethod: true
  Debug: false
  Permissions: true
  OpsAllPerms: false
  WorldGuardPVPIgnore: false
  WorldGuardPVPOnly: false
  FactionEnemyDrops: false
  DungeonMaze: false
  OfflineMode: false
  Residence: false
  ResidenceFlag: noscv
  LanguageFile: english.yml
  DropOnPVPDeath: false
  RestoreDelayTicks: 10
  BlackListWarn: false
  Enabled: false
Economy:
  Enabled: false
  Percent: false
  RestoreCost: 10.0
  MinCost: 5.0
  MaxCost: 0
  PercentCost: 5.0
  AddMin: false
  ChanceToDrop: 0
  DepositType: none
  DepositDestination: ''
  CountryCode: ''
  DecimalPlaces: 2
Messages:
  MsgHeader: '&7[&6Scavenger&7] &f'
  MsgRecovered: Your inventory has been restored.
  MsgSaving: Saving your inventory.
  MsgSaveForFee: Saving your inventory for a small fee of %COST% %CURRENCY%.
  MsgNotEnoughMoney: Item recovery cost is %COST% and you only have %BALANCE% %CURRENCY%.
    (%ERRORMESSAGE%)
  MsgInsidePA: You are inside PVP Arena %ARENA%. Scavenger will not save your inventory.
  MsgInsideBA: You are inside a Battle Arena. Scavenger will not save your inventory.
  MsgInsideMA: You are inside a Mob Arena. Scavenger will not save your inventory.
  MsgInsideWGPVP: You are inside a WorldGuard PVP region. Scavenger will not save
    your inventory.
  MsgInsideWGPVPOnly: You are not inside a WorldGuard PVP region. Scavenger will not
    save your inventory.
  MsgInsideEnemyFaction: You died in enemy territory. Your items will be dropped!
  MsgInsideDungeonMaze: You died in a DungeonMaze. Your items will be dropped!
  MsgInsideRes: This residence does not allow item recovery! Dropping items!
  MsgPVPDeath: Killed by another player! Dropping items.
  MsgBlacklistedWorld: Scavenger is disabled in this world. Be careful.
  MsgNoPerm: You do not have permissions to do this!
  MsgSelfRecoveryEnabled: You have enabled item recovery for yourself!
  MsgSelfRecoveryDisabled: You have disabled item recovery for yourself!
